apiVersion: v1
kind: Secret
metadata:
  name: my-acr-secret
  namespace: my-namespace
type: kubernetes.io/basic-auth
data:
  username: YWtzY29udGFpbmVyMjg=
  password: ZTdFR0JXMDltYkVIdm0rb01FYitPblE1K3k2a1NXdXBBYlIzSjN5ZE1WK0FDUkFYb2IvTQo=
