apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: my-namespace
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: test-secret28

      containers:

      - name: mysql-flask-ps
        image: akscontainer28.azurecr.io/mysql-python:v4
        ports:
        - containerPort: 5000
        env:
        - name: FLASK
          value: "production"

          # volumeMounts:
          # - name: data-volume
          #   mountPath: /azure/mnt
      # volumes:
      # - name: data-volume
      #   persistentVolumeClaim:
      #     claimName: my-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-namespace
spec:
  selector:
    app: flask-app

  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
  type: LoadBalancer 

